// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Usuario.Data.EF;

#nullable disable

namespace Usuario.Data.EF.Migrations
{
    [DbContext(typeof(UsuarioDbContext))]
    [Migration("20260308233806_perfilusuariorede")]
    partial class perfilusuariorede
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Usuario.Domain.Entity.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DS_PERFIL")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Perfil", (string)null);
                });

            modelBuilder.Entity("Usuario.Domain.Entity.PerfilUsuarioRede", b =>
                {
                    b.Property<int>("ID_PERFIL")
                        .HasColumnType("integer");

                    b.Property<int>("ID_USUARIO_REDE")
                        .HasColumnType("integer");

                    b.HasKey("ID_PERFIL", "ID_USUARIO_REDE");

                    b.HasIndex("ID_USUARIO_REDE");

                    b.ToTable("PerfilUsuarioRede");
                });

            modelBuilder.Entity("Usuario.Domain.Entity.Rede", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("DS_REDE")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Rede", (string)null);
                });

            modelBuilder.Entity("Usuario.Domain.Entity.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DS_EMAIL")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("DT_NASCIMENTO")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NM_USUARIO")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NR_CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<byte[]>("SALT")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("bytea");

                    b.Property<string>("SEG_SENHA")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("DS_EMAIL")
                        .IsUnique();

                    b.HasIndex("NR_CPF")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Usuario.Domain.Entity.UsuarioRede", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ID_REDE")
                        .HasColumnType("integer");

                    b.Property<int>("ID_USUARIO")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ID_REDE");

                    b.HasIndex("ID_USUARIO");

                    b.ToTable("UsuarioRede");
                });

            modelBuilder.Entity("Usuario.Domain.Entity.PerfilUsuarioRede", b =>
                {
                    b.HasOne("Usuario.Domain.Entity.Perfil", "Perfil")
                        .WithMany("perfilUsuarioRedes")
                        .HasForeignKey("ID_PERFIL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Usuario.Domain.Entity.UsuarioRede", "UsuarioRede")
                        .WithMany("perfilUsuarioRedes")
                        .HasForeignKey("ID_USUARIO_REDE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");

                    b.Navigation("UsuarioRede");
                });

            modelBuilder.Entity("Usuario.Domain.Entity.UsuarioRede", b =>
                {
                    b.HasOne("Usuario.Domain.Entity.Rede", "rede")
                        .WithMany("usuarioRedes")
                        .HasForeignKey("ID_REDE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Usuario.Domain.Entity.Usuario", "usuario")
                        .WithMany("usuarioRedes")
                        .HasForeignKey("ID_USUARIO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("rede");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("Usuario.Domain.Entity.Perfil", b =>
                {
                    b.Navigation("perfilUsuarioRedes");
                });

            modelBuilder.Entity("Usuario.Domain.Entity.Rede", b =>
                {
                    b.Navigation("usuarioRedes");
                });

            modelBuilder.Entity("Usuario.Domain.Entity.Usuario", b =>
                {
                    b.Navigation("usuarioRedes");
                });

            modelBuilder.Entity("Usuario.Domain.Entity.UsuarioRede", b =>
                {
                    b.Navigation("perfilUsuarioRedes");
                });
#pragma warning restore 612, 618
        }
    }
}
