// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Usuario.Data.EF;

#nullable disable

namespace Usuario.Data.EF.Migrations
{
    [DbContext(typeof(UsuarioDbContext))]
    [Migration("20260105014129_AddUser")]
    partial class AddUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Usuario.Domain.Entity.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DS_PERFIL")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("perfis");
                });

            modelBuilder.Entity("Usuario.Domain.Entity.PerfilUnidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ID_PERFIL")
                        .HasColumnType("integer")
                        .HasColumnName("ID_PERFIL");

                    b.Property<int>("ID_UNIDADE")
                        .HasColumnType("integer")
                        .HasColumnName("ID_UNIDADE");

                    b.HasKey("Id");

                    b.HasIndex("ID_PERFIL");

                    b.HasIndex("ID_UNIDADE");

                    b.ToTable("perfilUnidades");
                });

            modelBuilder.Entity("Usuario.Domain.Entity.PerfilUnidadeUsuario", b =>
                {
                    b.Property<int>("ID_PERFIL_UNIDADE")
                        .HasColumnType("integer")
                        .HasColumnName("ID_PERFIL_UNIDADE");

                    b.Property<int>("ID_USUARIO")
                        .HasColumnType("integer")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("ID_PERFIL_UNIDADE", "ID_USUARIO");

                    b.HasIndex("ID_USUARIO");

                    b.ToTable("perfilUnidadeUsuarios");
                });

            modelBuilder.Entity("Usuario.Domain.Entity.Unidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DS_UNIDADE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("unidades");
                });

            modelBuilder.Entity("Usuario.Domain.Entity.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DS_EMAIL")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("DT_NASCIMENTO")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NM_USUARIO")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NR_CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<byte[]>("SALT")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("bytea");

                    b.Property<string>("SEG_SENHA")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("DS_EMAIL")
                        .IsUnique();

                    b.HasIndex("NR_CPF")
                        .IsUnique();

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("Usuario.Domain.Entity.PerfilUnidade", b =>
                {
                    b.HasOne("Usuario.Domain.Entity.Perfil", "Perfil")
                        .WithMany("PerfilUnidades")
                        .HasForeignKey("ID_PERFIL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Usuario.Domain.Entity.Unidade", "Unidade")
                        .WithMany("PerfilUnidades")
                        .HasForeignKey("ID_UNIDADE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("Usuario.Domain.Entity.PerfilUnidadeUsuario", b =>
                {
                    b.HasOne("Usuario.Domain.Entity.PerfilUnidade", "PerfilUnidade")
                        .WithMany("perfilUnidadeUsuarios")
                        .HasForeignKey("ID_PERFIL_UNIDADE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Usuario.Domain.Entity.Usuario", "Usuario")
                        .WithMany("perfilUnidadeUsuarios")
                        .HasForeignKey("ID_USUARIO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilUnidade");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Usuario.Domain.Entity.Perfil", b =>
                {
                    b.Navigation("PerfilUnidades");
                });

            modelBuilder.Entity("Usuario.Domain.Entity.PerfilUnidade", b =>
                {
                    b.Navigation("perfilUnidadeUsuarios");
                });

            modelBuilder.Entity("Usuario.Domain.Entity.Unidade", b =>
                {
                    b.Navigation("PerfilUnidades");
                });

            modelBuilder.Entity("Usuario.Domain.Entity.Usuario", b =>
                {
                    b.Navigation("perfilUnidadeUsuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
