// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rede.Data.EF;

#nullable disable

namespace Rede.Data.EF.Migrations
{
    [DbContext(typeof(RedeDbContext))]
    [Migration("20260217223932_banco_rede")]
    partial class banco_rede
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rede.Domain.Entity.DiaVencimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Dia")
                        .HasColumnType("integer");

                    b.Property<int>("RedeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RedeId");

                    b.ToTable("DiaVencimento", (string)null);
                });

            modelBuilder.Entity("Rede.Domain.Entity.Rede", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DH_REGISTRO")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NR_CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .IsUnicode(true)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("RZ_SOCIAL")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ST_REDE")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<int>("US_REGISTRO")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Rede");
                });

            modelBuilder.Entity("Rede.Domain.Entity.Telefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NR_TELEFONE")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeId");

                    b.ToTable("Telefone");
                });

            modelBuilder.Entity("Rede.Domain.Entity.Unidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DH_REGISTRO")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DS_COMPLMENTO")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DS_ENDERECO")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NR_CEP")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("NR_UNIDADE")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("RedeId")
                        .HasColumnType("integer");

                    b.Property<string>("ST_UNIDADE")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<int>("US_REGISTRO")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RedeId");

                    b.ToTable("Unidade", (string)null);
                });

            modelBuilder.Entity("Rede.Domain.Entity.DiaVencimento", b =>
                {
                    b.HasOne("Rede.Domain.Entity.Rede", "Rede")
                        .WithMany("DiaVencimentos")
                        .HasForeignKey("RedeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ID_REDE");

                    b.Navigation("Rede");
                });

            modelBuilder.Entity("Rede.Domain.Entity.Telefone", b =>
                {
                    b.HasOne("Rede.Domain.Entity.Unidade", "Unidade")
                        .WithMany("Telefones")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ID_UNIDADE");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("Rede.Domain.Entity.Unidade", b =>
                {
                    b.HasOne("Rede.Domain.Entity.Rede", "Rede")
                        .WithMany("Unidades")
                        .HasForeignKey("RedeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("ID_REDE");

                    b.Navigation("Rede");
                });

            modelBuilder.Entity("Rede.Domain.Entity.Rede", b =>
                {
                    b.Navigation("DiaVencimentos");

                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("Rede.Domain.Entity.Unidade", b =>
                {
                    b.Navigation("Telefones");
                });
#pragma warning restore 612, 618
        }
    }
}
