// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rede.Data.EF;

#nullable disable

namespace Rede.Data.EF.Migrations
{
    [DbContext(typeof(RedeDbContext))]
    [Migration("20260503153334_ValueObjectTelefone")]
    partial class ValueObjectTelefone
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rede.Domain.Entity.Rede", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DH_REGISTRO")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NR_CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .IsUnicode(true)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("RZ_SOCIAL")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ST_REDE")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<int>("US_REGISTRO")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Rede");
                });

            modelBuilder.Entity("Rede.Domain.Entity.Unidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DH_REGISTRO")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DS_COMPLMENTO")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DS_ENDERECO")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ID_REDE")
                        .HasColumnType("integer");

                    b.Property<string>("NR_CEP")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("NR_UNIDADE")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ST_UNIDADE")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<int>("US_REGISTRO")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ID_REDE");

                    b.ToTable("Unidade", (string)null);
                });

            modelBuilder.Entity("Rede.Domain.Entity.Unidade", b =>
                {
                    b.HasOne("Rede.Domain.Entity.Rede", "Rede")
                        .WithMany("Unidades")
                        .HasForeignKey("ID_REDE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_REDE_UNIDADE");

                    b.OwnsMany("Rede.Domain.Entity.Telefone", "Telefones", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("ID_UNIDADE")
                                .HasColumnType("integer");

                            b1.Property<string>("NR_TELEFONE")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Numero");

                            b1.HasKey("Id");

                            b1.HasIndex("ID_UNIDADE");

                            b1.ToTable("UnidadeTelefones", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ID_UNIDADE");
                        });

                    b.Navigation("Rede");

                    b.Navigation("Telefones");
                });

            modelBuilder.Entity("Rede.Domain.Entity.Rede", b =>
                {
                    b.Navigation("Unidades");
                });
#pragma warning restore 612, 618
        }
    }
}
